project:
  type: website
  output-dir: docs

website:
  title: "HPC Workshop 1: Introduction to R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true